# Generated by Django 3.0.5 on 2020-04-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(db_column='device_id', primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('first_seen', models.DateTimeField(verbose_name='first_seen')),
                ('last_seen', models.DateTimeField(verbose_name='last_seen')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(db_column='port_id', primary_key=True, serialize=False)),
                ('port_num', models.IntegerField()),
                ('protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('first_seen', models.DateTimeField(verbose_name='first_seen')),
                ('last_seen', models.DateTimeField(verbose_name='last_seen')),
            ],
            options={
                'db_table': 'ports',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(db_column='sensor_id', primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('first_seen', models.DateTimeField(verbose_name='first_seen')),
                ('last_seen', models.DateTimeField(verbose_name='last_seen')),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('mac',), name='nk_sensor'),
        ),
        migrations.AddField(
            model_name='port',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_net_visibility_server.Device'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('mac',), name='nk_device'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(fields=('device', 'port_num'), name='nk_port'),
        ),
    ]
