# Generated by Django 5.2.5 on 2025-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_net_visibility_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='mac',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
