# Generated by Django 5.2.5 on 2025-08-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_net_visibility_server', '0002_alter_device_mac_alter_sensor_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port_num',
            field=models.IntegerField(db_index=True),
        ),
    ]
