# Generated by Django 5.2.5 on 2025-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_net_visibility_server', '0003_alter_port_port_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='mac',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('device', 'port_num')},
        ),
    ]
