# Generated by Django 6.0 on 2026-01-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_net_visibility_server', '0004_alter_device_mac_alter_sensor_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_notified_offline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_notified_offline'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_notified_timeout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_notified_timeout'),
        ),
    ]
